# This file is automatically generated by https://github.com/heroku/cli/blob/main/scripts/release/homebrew.js
# Do not update this file directly;
# Please update the template instead:
# https://github.com/heroku/cli/blob/main/scripts/release/homebrew/templates/heroku.rb
class Claire < Formula
  desc "CLaiRE CLI for use with CLaiRE SaaS API"
  homepage "https://claire.ac"
  url "https://github.com/CLaiRE-AC/CLaiRE/releases/download/v0.1.0/claire-v0.1.0-d4133e7a-x64.pkg"
  sha256 "c2f7e94fad9069bbc0fad0f6546dbdb01842a0ce0fdc466c1ea2a2b54b4c2dd9"
  version "0.1.0"
  version_scheme 1

  on_macos do
    on_arm do
      url "https://github.com/CLaiRE-AC/CLaiRE/releases/download/v0.1.0/claire-v0.1.0-d4133e7a-arm64.pkg"
      sha256 "195225ea700a385b1c04d6921f1964e810946b4a541b91ce5477dfd0e1aaff13"
    end
  end

  def install
    inreplace "bin/claire", /^CLIENT_HOME=/, "export CLAIRE_OCLIF_CLIENT_HOME=#{lib/"client"}\nCLIENT_HOME="
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/claire"

    # bash_completion.install libexec/"autocomplete-scripts/brew/bash" => "claire"
    # zsh_completion.install libexec/"autocomplete-scripts/brew/zsh/_claire"
  end

  def caveats; <<~EOS
    To use the CLaiRE CLI's autocomplete --
      Via homebrew's shell completion:
        1) Follow homebrew's install instructions https://docs.brew.sh/Shell-Completion
            NOTE: For zsh, as the instructions mention, be sure compinit is autoloaded
                  and called, either explicitly or via a framework like oh-my-zsh.
        2) Then run
          $ claire autocomplete --refresh-cache
      OR
      Use our standalone setup:
        1) Run and follow the install steps:
          $ claire autocomplete
  EOS
  end

  test do
    system bin/"claire", "version"
  end
end